apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: jira-sync
  name: jira-sync
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: jira-sync
      name: jira-sync
    spec:
      restartPolicy: Never
      containers:
      - name: root
        command:
        - ./jira-sync
        image: olsynt/jira-sync
        imagePullPolicy: Always
        env:
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "slack-webhook-url"
        - name: JIRA_USER
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "jira-user"
        - name: JIRA_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "jira-endpoint"
        - name: JIRA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "jira-api-token"
        - name: JIRA_START_DAY
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "jira-start-day"
        - name: TRELLO_APP_ID
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "trello-app-id"
        - name: TRELLO_BOARD_ID
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "trello-board-id"
        - name: TRELLO_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "trello-api-token"
        - name: TRELLO_LIST_ID
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "trello-list-id"
        - name: TRELLO_LABEL_IDS
          valueFrom:
            secretKeyRef:
              name: "jira-sync"
              key: "trello-label-ids"
        - name: RUN_IN_CLUSTER
          value: "true"
        - name: KUBE_NAMESPACE
          value: "default"
